spring:
  application:
    name=flight-schedule
  datasource:
    url: jdbc:postgresql://localhost:5432/airoport_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format-sql: true
server:
  port: 8090

